### ISSUE TITLE
Unable to run atomvm.packbeam

### ISSUE THREAD

**Issue by code-monad** [atomvm/exatomvm#57]
Following the guide provided in README, when I run `mix atomvm.packbeam`, it says:

```
** (ErlangError) Erlang error: :data_error
    :zlib.inflate_nif(#Reference<0.1871733751.2667708417.80571>, 8192, 16384, 0)
    :zlib.dequeue_all_chunks_1/3
    :zlib.inflate/3
    :zlib.uncompress/1
    (exatomvm 0.1.0) lib/packbeam.ex:20: ExAtomVM.PackBEAM.uncompress_literals/1
    (exatomvm 0.1.0) lib/packbeam.ex:38: ExAtomVM.PackBEAM.transform/1
    (exatomvm 0.1.0) lib/packbeam.ex:73: ExAtomVM.PackBEAM.pack_module/2
    (exatomvm 0.1.0) lib/packbeam.ex:136: anonymous fn/2 in ExAtomVM.PackBEAM.pack_files
```

what can be wrong? 

```
 ls -l avm_deps/
.rw-r--r--  12k code 12 8月  07:41  alisp.avm
.rw-r--r-- 391k code 12 8月  07:51  atomvmlib.avm
.rw-r--r-- 146k code 12 8月  07:42  estdlib.avm
.rw-r--r-- 7.2k code 12 8月  07:42  etest.avm
.rw-r--r-- 166k code 12 8月  07:42  exavmlib.avm
.rw-r--r--  432 code 12 8月  07:42  gleam_avm.avm
```

**Comment by code-monad** [comment]
and also:

```
mix atomvm.esp32.flash
** (ErlangError) Erlang error: :data_error
    :zlib.inflate_nif(#Reference<0.3711153805.4010409987.153718>, 8192, 16384, 0)
    :zlib.dequeue_all_chunks_1/3
    :zlib.inflate/3
    :zlib.uncompress/1
    (exatomvm 0.1.0) lib/packbeam.ex:20: ExAtomVM.PackBEAM.uncompress_literals/1
    (exatomvm 0.1.0) lib/packbeam.ex:38: ExAtomVM.PackBEAM.transform/1
    (exatomvm 0.1.0) lib/packbeam.ex:73: ExAtomVM.PackBEAM.pack_module/2
    (exatomvm 0.1.0) lib/packbeam.ex:136: anonymous fn/2 in ExAtomVM.PackBEAM.pack_files/1
```

**Comment by UncleGrumpy** [comment]
This an incompatibility with OTP-28 that is fixed by PR #53, which is waiting for review and should be merged soon.

**Comment by code-monad** [comment]
> This an incompatibility with OTP-28 that is fixed by PR [#53](https://github.com/atomvm/exatomvm/pull/53), which is waiting for review and should be merged soon.

Sounds good. But i manually pulled this pr and use it as my mix deps, the error seems still exists.

**Comment by code-monad** [comment]
> try `{:exatomvm, github: "petermm/ExAtomVM", branch: "fix-uncompressed-otp28-literals"},` and `mix deps.get` - `mix atomvm.packbeam`

This actually fix for me. thank you very much.

**Comment by code-monad** [comment]
I saw the PR is still open, is it about to merge?

**Comment by petermm** [comment]
soon, think the reviewer is afk - traveling currently, so merges will pick up soon..
